TMDT_04-main/TMDT_04-main/TMDT/Models/Publisher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TMDT.Models
{
    public class Publisher
    {
        [Key]
        public int PublisherID { get; set; }
        [Display(Name = "Tên nhà xuất bản")]

        [Required(ErrorMessage = "Tên nhà xuất bản là bắt buộc")]
        public string PublisherName { get; set; }
        [Display(Name = "Email")]
        [EmailAddress]
        public string PublisherEmail { get; set; }
        public ICollection<Book> Book { get; set; }

    }
}

TMDT_04-main/TMDT_04-main/TMDT/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    [AccessDeniedAuthorize(Roles = "NV_KHO")]
    public class PublishersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Publishers
        public ActionResult Index()
        {
            return View(db.Publisher.ToList());
        }

        // GET: Publishers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publisher.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // GET: Publishers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PublisherID,PublisherName,PublisherEmail")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                db.Publisher.Add(publisher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publisher.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PublisherID,PublisherName,PublisherEmail")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publisher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publisher.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Publisher publisher = db.Publisher.Find(id);
            db.Publisher.Remove(publisher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Publishers/Create.cshtml
@model TMDT.Models.Publisher

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PublisherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublisherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublisherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublisherEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublisherEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Publishers/Delete.cshtml
@model TMDT.Models.Publisher

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<h3>Bạn có chắc là xoá nhà xuất bản này không ?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublisherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublisherEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublisherEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TMDT_04-main/TMDT_04-main/TMDT/Views/Publishers/Details.cshtml
@model TMDT.Models.Publisher

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublisherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublisherEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublisherEmail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PublisherID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TMDT_04-main/TMDT_04-main/TMDT/Views/Publishers/Edit.cshtml
@model TMDT.Models.Publisher

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PublisherID)

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublisherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublisherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublisherEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublisherEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Publishers/Index.cshtml
@model IEnumerable<TMDT.Models.Publisher>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<button class="btn btn-default btn-sm" style="margin-bottom:10px">
    @Html.ActionLink("Create New", "Create")
</button>
<table class="table table-bordered" id="dataTable" width="100%" height="100%" cellspacing="2">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PublisherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublisherEmail)
            </th>
            <th></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PublisherName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublisherEmail)
                </td>
                <td>
                    <a href="@Url.Action("Edit","Publishers",new { id = item.PublisherID })" class="btn">
                        <i class="far fa-edit fa-2x" style="color: #F0AF83"></i>
                    </a>
                    <a href="@Url.Action("Details","Publishers",new { id = item.PublisherID })" class="btn">
                        <i class="fa fa-sticky-note fa-2x" style="color:#83d9dc" aria-hidden="true"></i>

                    </a>
                    <a href="@Url.Action("Delete","Publishers",new { id = item.PublisherID })" class="btn">
                        <i class="fa fa-trash fa-2x" style="color:#FF9AA2" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>