TMDT_04-main/TMDT_04-main/TMDT/Models/Provider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TMDT.Models
{
    public class Provider
    {
        [Key]
        public int ProviderID { get; set; }
        [Display(Name = "Tên nhà cung cấp")]
        [Required(ErrorMessage = "Tên nhà cung cấp là bắt buộc")]
        public string ProviderName { get; set; }
        [Display(Name = "Email")]
        [EmailAddress]
        public string ProviderEmail { get; set; }
        [Display(Name = "Phone")]
        [Phone]
        public string ProviderPhone { get; set; }
        [Display(Name = "Địa chỉ")]
        public string ProviderAddress { get; set; }
        public ICollection<Book> Book { get; set; }

    }
}

TMDT_04-main/TMDT_04-main/TMDT/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    [AccessDeniedAuthorize(Roles = "NV_KHO")]
    public class ProvidersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Providers
        public ActionResult Index()
        {
            return View(db.Provider.ToList());
        }

        // GET: Providers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Provider.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // GET: Providers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProviderID,ProviderName,ProviderEmail,ProviderPhone,ProviderAddress")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                db.Provider.Add(provider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(provider);
        }

        // GET: Providers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Provider.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProviderID,ProviderName,ProviderEmail,ProviderPhone,ProviderAddress")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(provider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(provider);
        }

        // GET: Providers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Provider.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Provider provider = db.Provider.Find(id);
            db.Provider.Remove(provider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Providers/Create.cshtml
@model TMDT.Models.Provider

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";


}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProviderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Providers/Delete.cshtml
@model TMDT.Models.Provider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h3>Bạn có chắc là xoá nhà cung cấp này?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderAddress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TMDT_04-main/TMDT_04-main/TMDT/Views/Providers/Details.cshtml
@model TMDT.Models.Provider

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Provider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderAddress)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProviderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TMDT_04-main/TMDT_04-main/TMDT/Views/Providers/Edit.cshtml
@model TMDT.Models.Provider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProviderID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TMDT_04-main/TMDT_04-main/TMDT/Views/Providers/Index.cshtml
@model IEnumerable<TMDT.Models.Provider>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


    <button class="btn btn-default btn-sm" style="margin-bottom:10px">
        @Html.ActionLink("Create New", "Create")
    </button>
    <table class="table table-bordered" id="dataTable" width="100%" height="100%" cellspacing="2">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProviderName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProviderEmail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProviderPhone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProviderAddress)
                </th>
                <th></th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProviderName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProviderEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProviderPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProviderAddress)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","Providers",new { id = item.ProviderID })" class="btn">
                            <i class="far fa-edit fa-2x" style="        color: #F0AF83"></i>
                        </a>
                        <a href="@Url.Action("Details","Providers",new { id = item.ProviderID })" class="btn">
                            <i class="fa fa-sticky-note fa-2x" style="color:#83d9dc" aria-hidden="true"></i>

                        </a>
                        <a href="@Url.Action("Delete","Providers",new { id = item.ProviderID })" class="btn">
                            <i class="fa fa-trash fa-2x" style="color:#FF9AA2" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
            }

    </table>